name: Build

on: [push, pull_request]

jobs:
  frontend:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]
    
    defaults:
      run:
        working-directory: ./frontend

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: ./frontend/package-lock.json
    - run: npm i

    - name: Test building frontend
      run: npm run build

  jar:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        java-version: [21]
        gradle-version: [8.14]

    steps:
    - uses: actions/checkout@v4
    - name: Use JDK ${{ matrix.java-version }}
      uses: actions/setup-java@v4
      with:
        java-version: ${{ matrix.java-version }}
        distribution: "microsoft"
    - name: Change wrapper permissions
      run: chmod +x ./gradlew

    - name: Building jar files
      run: ./gradlew clean build --refresh-dependencies --stacktrace
    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: opanel-jars
        path: ./build/libs/*